import { Event, EventUpdate } from '@/types';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Neon Valley Festival 2024',
    artist: 'Multiple Artists',
    venue: 'Desert Grounds',
    location: 'Los Angeles, CA',
    date: new Date('2024-08-12T18:00:00'),
    category: 'festival',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/screen%20%287%29-S2lu5BRa7T5VNlWfLEHcN8z8QgGQB7.png',
    description: 'Get ready for the most immersive electronic music experience of the year.',
    ticketSaleDate: new Date('2024-06-15T10:00:00'),
    presaleDate: new Date('2024-06-10T10:00:00'),
    ticketUrl: 'https://example.com/tickets',
    status: 'upcoming',
  },
  {
    id: '2',
    title: 'The Eras Tour',
    artist: 'Taylor Swift',
    venue: 'Wembley Stadium',
    location: 'London, UK',
    date: new Date('2024-08-05T19:00:00'),
    category: 'concert',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/screen%20%286%29-lnochKdTa5McsfZ94UdsbfnhNd5M60.png',
    description: 'Experience the journey through all musical eras.',
    ticketSaleDate: new Date('2024-05-20T10:00:00'),
    status: 'onsale',
  },
  {
    id: '3',
    title: 'Coachella 2024',
    artist: 'Various Artists',
    venue: 'Empire Polo Club',
    location: 'Indio, CA',
    date: new Date('2024-04-12T12:00:00'),
    category: 'festival',
    imageUrl: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/screen-r9GNl4tjjN2t38k53fA5mW9LTOsnZj.png',
    description: 'The premier music and arts festival returns.',
    ticketSaleDate: new Date('2024-01-15T12:00:00'),
    presaleDate: new Date('2024-01-12T12:00:00'),
    status: 'soldout',
  },
  {
    id: '4',
    title: 'Lakers vs. Warriors',
    venue: 'Crypto.com Arena',
    location: 'Los Angeles, CA',
    date: new Date('2024-11-10T19:30:00'),
    category: 'sports',
    imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800',
    description: 'NBA Regular Season showdown.',
    ticketSaleDate: new Date('2024-09-01T10:00:00'),
    status: 'upcoming',
  },
  {
    id: '5',
    title: 'The Lion King',
    venue: 'Lyceum Theatre',
    location: 'New York, NY',
    date: new Date('2024-12-04T20:00:00'),
    category: 'theater',
    imageUrl: 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=800',
    description: 'The award-winning musical spectacular.',
    ticketSaleDate: new Date('2024-10-01T10:00:00'),
    status: 'presale',
  },
  {
    id: '6',
    title: 'Neon Music Festival',
    artist: 'Multiple DJs',
    venue: 'Central Park',
    location: 'New York, NY',
    date: new Date('2024-09-14T18:00:00'),
    category: 'nightlife',
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800',
    description: 'Electronic music under the stars.',
    ticketSaleDate: new Date('2024-07-10T10:00:00'),
    presaleDate: new Date('2024-07-05T10:00:00'),
    status: 'upcoming',
  },
  {
    id: '7',
    title: 'Global Tech Summit 2024',
    venue: 'Convention Center',
    location: 'San Francisco, CA',
    date: new Date('2024-10-20T09:00:00'),
    category: 'festival',
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
    description: 'Leading tech conference and expo.',
    ticketSaleDate: new Date('2024-09-15T10:00:00'),
    status: 'upcoming',
  },
  {
    id: '8',
    title: 'Comedy Night Downtown',
    artist: 'Dave Chappelle',
    venue: 'Main St. Theater',
    location: 'Chicago, IL',
    date: new Date('2024-11-05T20:00:00'),
    category: 'comedy',
    imageUrl: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800',
    description: 'An evening of stand-up comedy.',
    ticketSaleDate: new Date('2024-10-01T10:00:00'),
    status: 'upcoming',
  },
  {
    id: '9',
    title: 'Burning Man Festival',
    venue: 'Black Rock Desert',
    location: 'Nevada',
    date: new Date('2024-08-25T12:00:00'),
    category: 'festival',
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
    description: 'Art, community, and self-expression.',
    ticketSaleDate: new Date('2024-04-20T12:00:00'),
    status: 'soldout',
  },
  {
    id: '10',
    title: 'Ultra Miami',
    artist: 'Multiple Artists',
    venue: 'Bayfront Park',
    location: 'Miami, FL',
    date: new Date('2024-03-22T14:00:00'),
    category: 'festival',
    imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
    description: 'Electronic music festival on the beach.',
    ticketSaleDate: new Date('2024-01-10T10:00:00'),
    status: 'onsale',
  },
];

export const mockUpdates: EventUpdate[] = [
  {
    id: '1',
    eventId: '1',
    eventTitle: 'Coachella',
    type: 'lineup',
    title: 'Tech Summit: Keynote speaker announced',
    description: 'Rumors circulating about a surprise guest appearance this Saturday.',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    priority: 'normal',
  },
  {
    id: '2',
    eventId: '10',
    eventTitle: 'Ultra Miami',
    type: 'lineup',
    title: 'Phase 2 lineup just dropped! See the full list of artists.',
    description: 'Check out the newly announced performers.',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    priority: 'important',
  },
  {
    id: '3',
    eventId: '6',
    eventTitle: 'Jazz Expo',
    type: 'alert',
    title: 'Neon Fest: Rain delay possible, check app',
    description: 'Weather update for outdoor festival.',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000), // 5 hours ago
    priority: 'urgent',
  },
  {
    id: '4',
    eventId: '8',
    eventTitle: 'Jazz Expo',
    type: 'tickets',
    title: 'Early bird tickets ending soon for Jazz Expo',
    description: 'Last chance to grab tickets at the early bird rate.',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    priority: 'important',
  },
  {
    id: '5',
    eventId: '9',
    eventTitle: 'Burning Man Festival',
    type: 'tickets',
    title: 'Camping passes are 50% sold out',
    description: 'If you are planning to stay on-site, grab your spot now.',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000), // 4 hours ago
    priority: 'normal',
  },
  {
    id: '6',
    eventId: '1',
    eventTitle: 'Neon Valley Festival 2024',
    type: 'tickets',
    title: 'Second wave pricing starts Friday',
    description: 'Early bird tier is officially closed. Prepare for the next wave.',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
    priority: 'normal',
  },
  {
    id: '7',
    eventId: '5',
    eventTitle: 'Electric Forest',
    type: 'logistics',
    title: 'New Parking Map Released',
    description: 'We have updated the parking zones to improve traffic flow.',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
    priority: 'normal',
  },
  {
    id: '8',
    eventId: '5',
    eventTitle: 'The Lion King',
    type: 'schedule',
    title: 'Set Time Update: Main Stage',
    description: 'Due to unforeseen weather conditions, the 5 PM slot has been moved.',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // yesterday
    priority: 'important',
  },
];
